service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: !GetAtt notesTable.Arn

functions:
  createNote:
    handler: index.createNote
    events:
      - http:
          method: post
          path: notes
  updateNote:
    handler: index.updateNote
    events:
      - http:
          method: put
          path: notes/{id}
  deleteNote:
    handler: index.deleteNote
    events:
      - http:
          method: delete
          path: notes/{id}
  getAllNotes:
    handler: index.getAllNotes
    events:
      - http:
          method: get
          path: notes
resources:
  Resources:
    notesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: notesId
            AttributeType: S
        KeySchema:
          - AttributeName: notesId
            KeyType: HASH
