service: serverless-test
frameworkVersion: '3'

custom:
  tableName: 'Giphy'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'lambda:InvokeFunction'
          Resource: '*'
        - Effect: Allow
          Action:
            - 'dynamodb:*'
          Resource: '*'
  environment:
    GIPHY_TABLE: ${self:custom.tableName}

functions:
  # myFunction1:
  #   handler: index.function1
  # myFunction2:
  #   handler: index.function2
  # createHandler:
  #   handler: index.createHandler
  # updateHandler:
  #   handler: index.updateHandler
  # getHandler:
  #   handler: index.getHandler
  # deleteHandler:
  #   handler: index.deleteHandler
  # getDataBySortKey:
  #   handler: index.getDataBySortKey
  # getDataByLocalIndex:
  #   handler: index.getDataByLocalIndex
  # getDataByGlobalIndex:
  #   handler: index.getDataByGlobalIndex
  # createUserHandler:
  #   handler: user.createUserHandler
  # # DYNAMODB EVENT STREAM
  # getUserHandler:
  #   handler: user.getUserHandler
  #   events:
  #     - stream:
  #         type: dynamodb
  #         # To GET ARN value ==> dynamodb --> Table --> Update ssettings --> Exports and Streams -->  DynamoDB stream details--> Turn on --> New Image
  #         arn: arn:aws:dynamodb:us-east-1:930277727374:table/userData/stream/2023-03-28T03:35:23.126
  #         # 1 dor 10 l orj irwel event gej vzne.
  #         batchSize: 10
  #         startingPosition: LATEST
  createGiphy:
    handler: api.createGiphy
    events:
      - http:
          method: post
          path: /giphy
          cors: true
  getSingleGiphy:
    handler: api.getSingleGiphy
    events:
      - http:
          method: get
          # dynamic param id
          path: /giphy/{id}
          cors: true

resources:
  Resources:
    # Table name --> Giphy
    Giphy:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Giphy
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          # HASH_KEY
          - AttributeName: giphyId
            AttributeType: S
        KeySchema:
          - AttributeName: giphyId
            KeyType: HASH
